[project]
name = "kapruka-gift-concierge"
version = "0.1.0"
description = "Backend with Multi-agent system for Kapruka Gift Concierge"
requires-python = ">=3.10,<3.13"
dependencies = [
    "loguru",
    "PyYAML",
    "python-dotenv",
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-openai",
    "openai",
    "qdrant-client",
    "fastembed",
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "passlib[bcrypt]",
    "python-jose[cryptography]",
    "python-multipart",
    "email-validator",
    "tzdata",
    "psycopg2-binary",
    "langfuse"
]

[dependency-groups]
dev = [
    "playwright",
    "jupyterlab",
    "ipykernel",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]